fix #18, add option to get state from file for cmd migrate
informartin/VeriSmart pull request #24
Opened 2021-02-26 12:04 UTC by thecodingshrimp

fixing issue #18 for now.

But, because get-state will be updated (see PR #23 for details) we can also leave this PR open until it is adapted to the changes.

2021-03-06 11:16 UTC, thecodingshrimp commented
This can now be merged after #26 is merged and #25 is closed.

2021-03-10 13:29 UTC, informartin requested changes

2021-03-10 13:29 UTC, informartin commented on cli/index-migrate
> +contractHelper.extractContractFromJSONFile(program.state_file)
It is kind of unintuitive that `extractContractFromJSONFile` is called even if no contract is extracted.

Wrapping the decision if the state is to be extracted from a JSON into a dedicated function may help here.

2021-03-10 13:29 UTC, informartin commented on cli/index-shared-attributes
> -        .option('-f, --file [optional]', 'Source file (csv) containing TXs to be replayed')
This change should also be reflected in the README.

2021-03-15 16:12 UTC, thecodingshrimp commented
Writing a big contract to file is now much much faster as well, fixing #28

2021-03-16 09:40 UTC, informartin approved these changes

2021-03-16 09:40 UTC, merged